name: 🧱 Build DLL (Windows)

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            # Step 1: 📥 Checkout your repository
            - name: 📥 Checkout repository (with submodules)
              uses: actions/checkout@v4
              with:
                  submodules: recursive # This ensures submodules are also initialized and updated

            # Step 2: 🧰 Set up vcpkg and install dependencies
            - name: 🧰 Set up vcpkg
              uses: lukka/run-vcpkg@v11
              with:
                  vcpkgJsonGlob: "**/vcpkg.json"
                  vcpkgGitCommitId: "96d5fb3de135b86d7222c53f2352ca92827a156b" # Your specific vcpkg commit
                  doNotCache: false

            # Step 3: 🛠️ Set up MSBuild
            - name: 🛠️ Set up MSBuild
              uses: microsoft/setup-msbuild@v2

            # Step 4: 🔨 Build the solution
            - name: 🔨 Build solution
              run: msbuild CustomQuickchat.sln /p:Configuration=Release /p:Platform=x64

            # Step 5: 📦 Upload build artifacts
            - name: 📦 Upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dll-and-pdb
                  path: |
                      CustomQuickchat/plugins/*.dll
                      CustomQuickchat/plugins/*.pdb
